---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "multitor-1"
  namespace: "default"
  labels:
    app: "multitor-1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "multitor-1"
  template:
    metadata:
      labels:
        app: "multitor-1"
    spec:
      containers:
      - name: "multitor"
        image: "gcr.io/august-tangent-228718/multitor"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "multitor-1-hpa"
  namespace: "default"
  labels:
    app: "multitor-1"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "multitor-1"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

