kind: Service
apiVersion: v1
metadata:
  name: "multitor"
spec:
  selector:
    app: "multitor-1"
  ports:
    - protocol: "TCP"
      port: 16379
      targetPort: 16379
      nodePort: 30069
  type: LoadBalancer